name: Auto Download
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "13 14 * * *"
jobs:
  BingWallPaperAutoDownload:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Set python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests
      - name: 'Start Download'
        run: python main.py
      - name: 'Commit files'
        run: |
          git config --global user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Auto Fetch Bing Wallpaper." -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSON_TOKEN }}
          branch: 'master'
